services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
      - ./initdb.d/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: motdepasse
      POSTGRES_USER: eliot
      POSTGRES_DB: projet-final-back

volumes:
  pg_data:
    name: "projet-final-back"
